default: &default

  available_locales:
    - en
    - de
    # - alias

  # grid, list and/or map
  view_modes:
    - list

  default_locale: en

  # use 2- or 3-letter country-code
  # have a look at https://github.com/alphabetum/iso-639 for possible methods
  alpha: 'alpha2'
  # alpha: 'alpha3_terminologic'

  media_streams:
    defaults:
      video: 480p
      audio: 192k
    video:
      240p: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_sd240p.mp4
      480p: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_sd480p.mp4
      720p: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_sd720p.mp4
    audio:
      128k: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_128k.mp3
      192k: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_192k.mp3
      256k: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_256k.mp3

  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interview'
    transcriptor: 'transcript'
    translator: 'translation'
    segmentator: 'segmentation'
    cinematographer: 'Camera recorder'
    quality_manager: 'Quality management interviewing'
    proofreader: 'proof_reading' 

  upload_types:
    - bulk_metadata
    - bulk_texts

  project_name: # Will be used in titles, emails, etc.
    en: 'Accessing Campscapes: Inclusive Strategies for Using European Conflicted Heritage.'
    de: 'Accessing Campscapes: Inclusive Strategies for Using European Conflicted Heritage.'

  project_id: 'campscapes'

  # used in PDFs
  # give the color code as fractions of 255
  # e.g. '143, 32, 28' ==> '0.560784314, 0.125490196, 0.109803922'
  primary_color_rgb: '0,0.43529411764705883,0.7176470588235294'

  project_shortname: 'CAMPSCAPES'

  project_initials: 'CS' # Use two upper case initials. These will be used for file names, interview id's, etc. So please choose carefully. This cannot be changed later.

  project_domain: ''

  archive_domain: 'http://testimonies.campscapes.org'

  project_doi: ''

  is_catalog: true

  # TODO: Umstellen russ. Links, s. kommentierte Links unten.
  external_links:
    conditions: #nutzungsbedingungen:
      en: 'http://www.campscapes.org/terms-and-conditions/'
      de: 'http://www.campscapes.org/terms-and-conditions/'
    # request_for_use: #nutzungsantrag:
    #   en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/archivmaterial/index.html'
      # ru: 'http://www.zwangsarbeit-archiv.de/ru/sammlung/nutzungsbedingungen/archivmaterial/index.html'
    privacy_protection: #datenschutzbestimmungen:
      en: 'http://www.campscapes.org/privacy-policy/'
      de: 'http://www.campscapes.org/privacy-policy/'
    # annotation_guidelines:
    #   en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/anmerkungen-richtlinien/index.html'
    # team:
    #   en: 'http://www.zwangsarbeit-archiv.de/en/team'
    contact: #kontakt:
      en: ' https://www.cedis.fu-berlin.de/services/projektentwicklung/aktuell/ic-access/index.html'
      de: ' https://www.cedis.fu-berlin.de/services/projektentwicklung/aktuell/ic-access/index.html'
    legal_info: #impressum:
      en: 'http://www.campscapes.org/'
      de: 'http://www.campscapes.org/'

  # Please mount the CIFS storage server locally like this (read-only for normal users!):
  # sudo mkdir -p /mnt/eaz-diga.cedis.fu-berlin.de/data
  # /etc/fstab:
  #     //eaz-diga.cedis.fu-berlin.de/data /mnt/eaz-diga.cedis.fu-berlin.de/data cifs noauto,sec=ntlmv2,credentials=/etc/cifs.credentials,uid=root,gid=root,nosetuids,file_mode=0644,dir_mode=0755 0 0
  # /etc/cifs.credentials (create the file with permissions 600 and enter your CIFS credentials)
  #     username=...
  #     password=...
  # If you want to simulate the mount locally you can either place a symlink or mount --bind
  cifs_share: '/mnt/eaz-diga.cedis.fu-berlin.de/data/'

  storage_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup'
  photo_storage_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/bilder'
  archive_management_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/redaktionssystem'
  repository_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/archiv_dis'

  streaming_server: 'rtmpt://stream.cedis.fu-berlin.de/zwangsarbeit-archiv'

  video_src_base: "https://medien.cedis.fu-berlin.de/zwar/zwar"

  meta_keywords:
    de: 'Speer, Befreiung, Zwangsarbeit, Sklavenarbeit, Geschichte, Nationalsozialismus, Hitler, Sauckel, Oral History, biographisch, Archiv, Gedenken, Literatur, Quellen, Interviews, Erinnerungen, Stimmen, Fotografien, Entschädigung, Konzentrationslager, KZ, Ukrainerinnen, Tschechen, Polen, Ostarbeiter, Ostarbeiterinnen, Stiftung EVZ, audiovisuelle Archive, multimedial, Inventarisierung, Museum, Universität, Digitalisierung, Segmentierung, Übersetzung, STO, IMI, Militärinternierte, Auschwitz, Buchenwald, Flossenbürg, Zigeuner, Roma, Sinti, Displaced Person, Zwangsarbeiterlager, Zweiter Weltkrieg, Drittes Reich, 1939, 1940, 1941, 1942, 1943, 1944, 1945, Ghetto, Arbeitserziehungslager, Vernichtung, Verfolgung, Widerstand, Litauen, Moldawien, Ukraine, Polen, Italien, Norwegen, vergessene Opfer, Kriegskinder, Germanisierung, Deportation, Platoprojekt, Alexander von Plato, Fernuniversität, Hitlers Sklaven, SS, Gestapo, Wehrmacht'
    en: 'audiovisual oral history archive, forced labor, 1939-1945, 3rd Reich'
    ru: '##ru##'

  contact_email: 'mail@zwangsarbeit-archiv.de'

  smtp_server: 'mail.fu-berlin.de'

  # Interview partner properties usually depend on the historical context and must therefore be configured
  # on a per-project basis:
  # - To create a property from sub-entries of a registry entry, use the (default language) descriptor to identify the
  #   entry. The ID of the property will define the internal property name.
  # - To create a property from references of a certain reference type, use the registry reference code
  #   as ID. The clear name will be retrieved from the registry reference type table.
  # - Interview partner properties will be used as search facets when setting the facet property to 'true'. The order of
  #   entries is significant to determine in which order entries appear in the "search facet" section.
  # NB: Only properties from a 'registry entry' or 'registry reference type' source can be used as facet entries.

  metadata_fields: 
    - 
      name: camps
      source: registry_entry
      label: 
        de: Lager
        en: Camp
      display_on_landing_page: true
      use_in_results_table: true
      use_as_facet: true
    - 
      name: language
      source: language
      use_in_results_table: true
      label: 
        de: Sprache
        en: Language
    - 
      name: language_id
      source: language
      use_as_facet: true
      label: 
        de: Sprache
        en: Language
    - 
      name: groups
      source: registry_entry
      display_on_landing_page: true
      use_in_results_table: true
      use_as_facet: true
      label: 
        de: Gruppe
        en: Group
    - 
      name: media_type
      source: interview
      use_as_facet: false
    - 
      name: gender
      source: person
      use_as_facet: false
      use_in_details_view: true
      display_on_landing_page: true
      label:
        de: Geschlecht
        en: Gender
      values: 
        female: female
        male: male
    - 
      name: date_of_birth
      source: person
      use_as_facet: false
      display_on_landing_page: true
      use_in_details_view: true
      label:
        de: Geburtsdatum
        en: Date of Birth
    - 
      name: year_of_birth
      source: person
      use_as_facet: false
      display_on_landing_page: true
      use_in_details_view: true
      label:
        de: Geburtsjahr
        en: Year of Birth
    - 
      name: country_of_birth
      source: person
      use_as_facet: false
      use_in_results_table: false
      use_in_details_view: true
      label: 
        de: Herkunftsland
        en: Country of Birth
    - 
      name: birth_location
      source: registry_reference_type
      ref_object_type: person
      display_on_landing_page: true
      use_as_facet: false
      label: 
        de: Geburtsort
        en: Place of Birth
    - 
      name: collection_id
      source: collection
      label: 
        de: Sammlung
        en: Collection
      use_in_results_table: true
      use_as_facet: true
    - 
      name: group_details
      source: registry_entry
      display_on_landing_page: true
      use_as_facet: false
    - 
      name: interview_location
      source: registry_reference_type
      ref_object_type: interview
      use_as_facet: false
      display_on_landing_page: true
      use_in_results_table: false
      label:
        de: Ort des Interviews
        en: Interview location
    - 
      name: accessibility
      source: registry_entry
      use_as_facet: true
      display_on_landing_page: true
      use_in_details_view: true
      use_in_results_table: true
      label:
        de: Zugänglichkeit
        en: Accessibility

  fullname_on_landing_page: true

  has_newsletter: true

  pdf_registry_entry_codes:
    - camps
    - companies
    - people

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
