default: &default

  available_locales:
    - de
    - en
    - ru
    # - alias

  default_locale: de

  # use 2- or 3-letter country-code
  # have a look at https://github.com/alphabetum/iso-639 for possible methods
  alpha: 'alpha2'
  # alpha: 'alpha3_terminologic'

  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interview'
    transcriptor: 'transcript'
    translator: 'translation'
    segmentator: 'segmentation'
    cinematographer: 'Camera recorder'
    quality_manager: 'Quality management interviewing'
    proofreader: 'proof_reading' 

  upload_types:
    - campscape
    - protocols

  project_name: # Will be used in titles, emails, etc.
    de: 'Zwangsarbeit 1939-1945. Erinnerungen und Geschichte.'
    en: 'Forced Labor 1939-1945. Memory and History.'
    ru: 'Принудительный труд 1939-1945. Воспоминания и история.'

  project_id: 'zwar'

  project_shortname: 'ZWAR'

  project_initials: 'ZA' # Use two upper case initials. These will be used for file names, interview id's, etc. So please choose carefully. This cannot be changed later.

  project_domain: 'zwangsarbeit-archiv.de'

  archive_domain: 'zwangsarbeit-archiv.de/archiv'

  project_doi: '10.5072'

  # TODO: Umstellen russ. Links, s. kommentierte Links unten.
  external_links:
    conditions: #nutzungsbedingungen:
      de: 'http://www.zwangsarbeit-archiv.de/sammlung/nutzungsbedingungen/index.html'
      en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/index.html'
      ru: 'http://www.zwangsarbeit-archiv.de/ru/sammlung/nutzungsbedingungen/index.html'
    request_for_use: #nutzungsantrag:
      de: 'http://www.zwangsarbeit-archiv.de/sammlung/nutzungsbedingungen/archivmaterial/index.html'
      en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/archivmaterial/index.html'
      # ru: 'http://www.zwangsarbeit-archiv.de/ru/sammlung/nutzungsbedingungen/archivmaterial/index.html'
    privacy_protection: #datenschutzbestimmungen:
      de: 'http://www.zwangsarbeit-archiv.de/sammlung/nutzungsbedingungen/hinweise_zum_datenschutz/index.html'
      en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/hinweise_zum_datenschutz/index.html'
      # ru: 'http://www.zwangsarbeit-archiv.de/ru/sammlung/nutzungsbedingungen/hinweise_zum_datenschutz/index.html'
    annotation_guidelines:
      de: 'http://www.zwangsarbeit-archiv.de/sammlung/nutzungsbedingungen/anmerkungen-richtlinien/index.html'
      en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/anmerkungen-richtlinien/index.html'
      #ru: 'http://www.zwangsarbeit-archiv.de/ru/sammlung/nutzungsbedingungen/anmerkungen-richtlinien/index.html'
    team:
      de: 'http://www.zwangsarbeit-archiv.de/team'
      en: 'http://www.zwangsarbeit-archiv.de/en/team'
      #ru: 'http://www.zwangsarbeit-archiv.de/ru/team'
    contact: #kontakt:
      de: 'http://www.zwangsarbeit-archiv.de/kontakt'
      en: 'http://www.zwangsarbeit-archiv.de/en/kontakt'
      ru: 'http://www.zwangsarbeit-archiv.de/ru/kontakt'
    legal_info: #impressum:
      de: 'http://www.zwangsarbeit-archiv.de/impressum'
      en: 'http://www.zwangsarbeit-archiv.de/en/impressum'
      ru: 'http://www.zwangsarbeit-archiv.de/ru/impressum'

  # Please mount the CIFS storage server locally like this (read-only for normal users!):
  # sudo mkdir -p /mnt/eaz-diga.cedis.fu-berlin.de/data
  # /etc/fstab:
  #     //eaz-diga.cedis.fu-berlin.de/data /mnt/eaz-diga.cedis.fu-berlin.de/data cifs noauto,sec=ntlmv2,credentials=/etc/cifs.credentials,uid=root,gid=root,nosetuids,file_mode=0644,dir_mode=0755 0 0
  # /etc/cifs.credentials (create the file with permissions 600 and enter your CIFS credentials)
  #     username=...
  #     password=...
  # If you want to simulate the mount locally you can either place a symlink or mount --bind
  cifs_share: '/mnt/eaz-diga.cedis.fu-berlin.de/data/'

  storage_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup'
  photo_storage_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/bilder'
  archive_management_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/redaktionssystem'
  repository_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/archiv_dis'

  streaming_server: 'rtmpt://stream.cedis.fu-berlin.de/zwangsarbeit-archiv'

  video_src_base: "https://medien.cedis.fu-berlin.de/zwar/zwar"

  meta_keywords:
    de: 'Speer, Befreiung, Zwangsarbeit, Sklavenarbeit, Geschichte, Nationalsozialismus, Hitler, Sauckel, Oral History, biographisch, Archiv, Gedenken, Literatur, Quellen, Interviews, Erinnerungen, Stimmen, Fotografien, Entschädigung, Konzentrationslager, KZ, Ukrainerinnen, Tschechen, Polen, Ostarbeiter, Ostarbeiterinnen, Stiftung EVZ, audiovisuelle Archive, multimedial, Inventarisierung, Museum, Universität, Digitalisierung, Segmentierung, Übersetzung, STO, IMI, Militärinternierte, Auschwitz, Buchenwald, Flossenbürg, Zigeuner, Roma, Sinti, Displaced Person, Zwangsarbeiterlager, Zweiter Weltkrieg, Drittes Reich, 1939, 1940, 1941, 1942, 1943, 1944, 1945, Ghetto, Arbeitserziehungslager, Vernichtung, Verfolgung, Widerstand, Litauen, Moldawien, Ukraine, Polen, Italien, Norwegen, vergessene Opfer, Kriegskinder, Germanisierung, Deportation, Platoprojekt, Alexander von Plato, Fernuniversität, Hitlers Sklaven, SS, Gestapo, Wehrmacht'
    en: 'audiovisual oral history archive, forced labor, 1939-1945, 3rd Reich'
    ru: '##ru##'

  contact_email: 'mail@zwangsarbeit-archiv.de'

  smtp_server: 'mail.fu-berlin.de'

  # Interview partner properties usually depend on the historical context and must therefore be configured
  # on a per-project basis:
  # - To create a property from sub-entries of a registry entry, use the (default language) descriptor to identify the
  #   entry. The ID of the property will define the internal property name.
  # - To create a property from references of a certain reference type, use the registry reference code
  #   as ID. The clear name will be retrieved from the registry reference type table.
  # - Interview partner properties will be used as search facets when setting the facet property to 'true'. The order of
  #   entries is significant to determine in which order entries appear in the "search facet" section.
  # NB: Only properties from a 'registry entry' or 'registry reference type' source can be used as facet entries.

  person_properties:
    - id: 'person_reference'
      source: 'registry_entry'
    - id: 'forced_labor_groups'
      source: 'registry_entry'
      use_as_facet: true
      display_on_landing_page: true`
    - id: 'forced_labor_fields'
      source: 'registry_entry'
      use_as_facet: true
    - id: 'language_id'
      source: 'language'
      use_as_facet: true
    - id: 'year_of_birth'
      source: 'person'
      use_as_facet: true
    - id: 'gender'
      source: 'person'
      use_as_facet: true
      values:
        female: 'female'
        male: 'male'
    - id: 'collection_id'
      source: 'collection'
      use_as_facet: true 
    - id: 'media_type'
      source: 'interview'
      use_as_facet: true
    - id: 'birth_location'
      source: 'registry_reference_type'
      use_as_facet: false
      display_on_landing_page: false
    - id: 'forced_labor_habitations'
      source: 'registry_entry'
      # use_as_facet: true
    - id: 'home_location'
      source: 'registry_reference_type'
      use_as_facet: false
    - id: 'forced_labor_location'
      source: 'registry_reference_type'
      use_as_facet: false
    - id: 'deportation_location'
      source: 'registry_reference_type'
      use_as_facet: false
    - id: 'return_location'
      source: 'registry_reference_type'
      use_as_facet: false

  # NB: The map has not yet been generalized to work for all historical
  # contexts. It relies on ZWAR-specific registry data structures (i.e. a
  # three-level location hierarchy, companies, camps and specific registry
  # reference types like "forced labor locations").
  # If you want to use the map for a different historical context then a
  # generic map will have to be specified by the project responsibles first.
  # Therefore set this to "false" for all projects except ZWAR unless
  # you also change the corresponding map code.
  uses_map: true

  has_newsletter: true

  hidden_registry_entry_ids:
    - 28205
    - 28221
    - 28237

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

