production:
  auto_commit_after_request: true
  auto_commit_after_delete_request: true
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  auto_commit_after_request: true
  auto_commit_after_delete_request: true
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: solr
    port: 8983
    log_level: INFO
    path: /solr/default

test:
  auto_commit_after_request: true
  auto_commit_after_delete_request: true
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/default
